settings:
  title: 'Hyperbeam Status Page'
  url: 'https://status.hyperbeam.com' # used for Slack messages
  logo: logo.svg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: engine-heartbeat # unique identifier
    name: Dispatch API
    description: '' # default=empty
    url: 'https://engine.hyperbeam.com/ok' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: na-heartbeat
    name: NA Region
    description: ''
    url: 'https://engine.hyperbeam.com/vm/ok?reg=NA'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: eu-heartbeat
    name: EU Region
    description: ''
    url: 'https://engine.hyperbeam.com/vm/ok?reg=EU'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: as-heartbeat
    name: AS Region
    description: ''
    url: 'https://engine.hyperbeam.com/vm/ok?reg=AS'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: na-gpu-heartbeat
    name: NA GPU Region
    description: ''
    url: 'https://engine.hyperbeam.com/vm/ok?reg=NA&gpu'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: eu-gpu-heartbeat
    name: EU GPU Region
    description: ''
    url: 'https://engine.hyperbeam.com/vm/ok?reg=EU&gpu'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: as-gpu-heartbeat
    name: AS GPU Region
    description: ''
    url: 'https://engine.hyperbeam.com/vm/ok?reg=AS&gpu'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: hyperbeam-heartbeat
    name: Watch Party
    description: ''
    url: 'https://api.hyperbeam.com/heartbeat'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
