settings:
  title: 'Status Page'
  url: 'https://status.hyperbeam.com' # used for Slack messages
  logo: logo.svg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: hyperbeam-heartbeat # unique identifier
    name: Hyperbeam Watch Party
    description: '' # default=empty
    url: 'https://api.hyperbeam.com/heartbeat' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: engine-heartbeat # unique identifier
    name: Hyperbeam API Production
    description: '' # default=empty
    url: 'https://engine.hyperbeam.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
  - id: enginetest-heartbeat # unique identifier
    name: Hyperbeam API Testing
    description: '' # default=empty
    url: 'https://enginetest.hyperbeam.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 404 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
